/* Bundle the shared tax core for the browser.
 *   packages/tax-core/src/browser.js  →  assets/tax-core.js  (classic script, IIFE)
 *
 * The website is static (GitHub Pages serves the repo root), so the bundle is
 * committed. `npm test` fails if it is stale — edit the core, then run
 * `npm run build:core` (or `npm run build:all`). Never edit the output by hand.
 */
import { build } from 'esbuild';
import { writeFileSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

export const OUT = fileURLToPath(new URL('../assets/tax-core.js', import.meta.url));
const ENTRY = fileURLToPath(new URL('../packages/tax-core/src/browser.js', import.meta.url));

export const BANNER = '/* GENERATED by scripts/build-core.mjs from packages/tax-core — do not edit by hand.\n' +
  '   Tax.cal tax engine for the browser. Source of truth: packages/tax-core/src. */';

export async function bundleCore() {
  const res = await build({
    entryPoints: [ENTRY],
    bundle: true,
    format: 'iife',
    target: ['es2019'],
    platform: 'browser',
    write: false,
    legalComments: 'none',
    charset: 'utf8',
    banner: { js: BANNER }
  });
  return res.outputFiles[0].text;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const js = await bundleCore();
  let prev = '';
  try { prev = readFileSync(OUT, 'utf8'); } catch (e) {}
  writeFileSync(OUT, js);
  console.log((prev === js ? 'unchanged ' : 'wrote ') + 'assets/tax-core.js (' + js.length + ' bytes)');
}
